routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('frontend.index');
// });

Route::get('/','HomeController@index')->name('home');
Route::get('/single-post/{id}','HomeController@singlePost')->name('single_post');

Route::group(['middleware' => 'auth'], function(){
    
    Route::get('/admin','DashboardController@index')->name('dashboard');
    Route::resource('/tag','TagController');
    Route::resource('/category','CategoryController');
    Route::resource('/post','PostController');
});




Auth::routes();    

resources/views/backend/layouts/partials/footer.blade.php
 <!-- Footer -->
 <footer class="site-footer">
    <div class="footer-inner bg-white">
        <div class="row">
            <div class="col-sm-6">
                Copyright &copy; 2018 Ela Admin
            </div>
            <div class="col-sm-6 text-right">
                Designed by <a href="https://colorlib.com">Colorlib</a>
            </div>
        </div>
    </div>
</footer>
<!-- /.site-footer -->

resources/views/backend/layouts/partials/header.blade.php
 <!-- Header-->
 <header id="header" class="header">
    <div class="top-left">
        <div class="navbar-header">
        <a class="navbar-brand" href="{{ route('dashboard')}}"><span>Blog</span></a>
             <a class="navbar-brand hidden" href="./"><img src="{{asset('ui/backend/images/logo2.png')}}" alt="Logo"></a>
            <a id="menuToggle" class="menutoggle"><i class="fa fa-bars"></i></a>
        </div>
    </div>
    <div class="top-right">
        <div class="header-menu">
            <div class="header-left">
                <button class="search-trigger"><i class="fa fa-search"></i></button>
                <div class="form-inline">
                    <form class="search-form">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search ..." aria-label="Search">
                        <button class="search-close" type="submit"><i class="fa fa-close"></i></button>
                    </form>
                </div>

        
            </div>

            <div class="user-area dropdown float-right">
                <a href="#" class="dropdown-toggle active" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="user-avatar rounded-circle" src="{{asset('ui/backend/images/admin.jpg')}}" alt="User Avatar">
                </a>

                <div class="user-menu dropdown-menu">
                    <a class="nav-link" href="{{ route('logout') }}"   onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();">
                        <i class="fa fa-power -off"></i>Logout</a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                </div>
            </div>

        </div>
    </div>
</header>
<!-- /#header -->

resources/views/backend/layouts/partials/sidebar.blade.php
 <!-- Left Panel -->
    <aside id="left-panel" class="left-panel">
        <nav class="navbar navbar-expand-sm navbar-default">
            <div id="main-menu" class="main-menu collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active">
                    <a href="{{ route('dashboard')}}"><i class="menu-icon fa fa-laptop"></i>Dashboard </a>
                    </li>
                    <li>
                    <a href="{{ route('category.index') }}"><i class="menu-icon fa fa-folder-open"></i>Category </a>
                    </li>
                    <li>
                        <a href="{{ route('tag.index') }}"><i class="menu-icon fa  fa-tags"></i>Tag </a>
                    </li>
                    <li>
                        <a href="{{ route('post.index') }}"><i class="menu-icon fa fa-laptop"></i>Article </a>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </nav>
    </aside>
    <!-- /#left-panel -->