routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('frontend.index');
// });

Route::get('/','HomeController@index')->name('home');
Route::get('/single-post/{id}','HomeController@singlePost')->name('single_post');

Route::group(['middleware' => 'auth'], function(){
    
    Route::get('/admin','DashboardController@index')->name('dashboard');
    Route::resource('/tag','TagController');
    Route::resource('/category','CategoryController');
    Route::resource('/post','PostController');
});




Auth::routes();    

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $guarded = [];

    public function category(){
        return $this->belongsTo(Category::class,'cat_id','id');
    }

    public function tags(){
        return $this->belongsToMany(Tag::class)->withTimestamps();
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use App\Post;
use App\Category;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;

class PostController extends Controller
{

    const UPLOAD_DIR = '/uploads/post/';

    public function index(){
        $paginatePerPage = 10;
            $pagenumber = request('page');
            if ($pagenumber > 1) {
                $serial = ($pagenumber * $paginatePerPage) - $paginatePerPage;
            } else {
                $serial = 0;
            }
        $data = Post::paginate($paginatePerPage);
        return view('backend.post.index',compact('data','serial'));
    }

    public function create(){
        $categorys = Category::all();
        $tags      = Tag::all();

        $data = [
            'categorys' => $categorys,
            'tags'      => $tags,
        ];
        return view('backend.post.create',compact('data'));
    }

    public function store(Request $request){
        $data = $request->all();
    
       if($request->hasFile('image')){
             $data['image'] = $this->uploadImage($request->image);
       }

    
      $data = Post::create([
           'title'  => $data['title'],
           'cat_id' => $data['cat_id'],
           'image'  => $data['image'],
           'body'   => $data['body'],
       ]);

       $data->tags()->attach($request->tags);
       
       return redirect()->route('post.index')->with('status','Post Created Successfully!');
    }

    public function edit($id){
        $post = Post::findorfail($id);
        $categorys = Category::all();
        $tags      = Tag::all();

        return view('backend.post.edit',compact('post','categorys','tags'));
    }

    public function update(Request $request,$id){
        $data = $request->all();
        $post = Post::findorfail($id);

        if($request->hasFile('image')){
            $image_path = public_path() . '/uploads/post/' . $post->image;
            unlink($image_path);
            $data['image'] = $this->uploadImage($request->image);
       }else{
           $data['image']  = $post->image;
       }

        $post->title  = $request->title;
        $post->cat_id = $request->cat_id;
        $post->image  = $data['image'];
        $post->body   = $request->body;

        $post->save();
        $post->tags()->sync($request->tags);

        return redirect()->route('post.index')->with('status','Post Updated Successfully!');
    }

    public function destroy($id){
        $post = Post::findorfail($id);
        $image_path = public_path() . '/uploads/post/' . $post->image;
        unlink($image_path);
        $post->delete();

        $post->tags()->detach();

        return redirect()->route('post.index')->with('status','Post Deleted Successfully!');
    }

    private function uploadImage($file) //$name
    {
        $extension = $file->getClientOriginalExtension($file);
        $fileName = date('y-m-d') . '_' . time() . '.' . $extension; //'_' . $name .
        Image::make($file)->resize(1170, 760)->save(public_path() . self::UPLOAD_DIR . $fileName);
        return $fileName;
    }  
}

resources/views/backend/post/create.blade.php
@extends('backend.layouts.master')

@push('title','Post')

@push('css')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
@endpush

@section('content')
    
<div class="animated fadeIn">

    <div class="row">

        <div class="col-lg-12">
            <div class="card">
                <div class="card-body card-header">
                    <h4 class="box-title">Post </h4>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card-body">
                                @if (session('status'))
                                <div class="alert alert-success">
                                    {{ session('status') }}
                                </div>
                            @endif
                            <form action="{{ route('post.store') }}" method="post" enctype="multipart/form-data">
                                @csrf
                                    <div class="form-group has-success">
                                        <div class="row">
                                            <div class="col-md-2">
                                                <label for="title" class="mt-2">Title</label>
                                            </div>
                                            <div class="col-md-10">
                                                <input id="title" name="title" type="text" class="form-control" placeholder="Enter Title">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group has-success">
                                        <div class="row">
                                            <div class="col-md-2">
                                                <label for="cat" class="mt-2">Category</label>
                                            </div>
                                            <div class="col-md-4">
                                                <select class="form-control" name="cat_id" id="cat">
                                                    @foreach ($data['categorys'] as $item)
                                                        <option value="{{ $item->id}}">{{ $item->name }}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group has-success">
                                        <div class="row">
                                            <div class="col-md-2">
                                                <label for="tag" class="mt-2">Tag</label>
                                            </div>
                                            <div class="col-md-4">
                                                @foreach ($data['tags'] as $item)
                                                    <input type="checkbox" name='tags[]' value="{{$item->id}}" class="mr-2">{{$item->name}}
                                                @endforeach
                                                
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group has-success">
                                        <div class="row">
                                            <div class="col-md-2">
                                                <label class="mt-2">Image</label>
                                            </div>
                                            <div class="col-md-4">
                                               <input type="file" name="image">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group has-success">
                                        <div class="row">
                                            <div class="col-md-2">
                                                <label for="text" class="mt-2">Body</label>
                                            </div>
                                            <div class="col-md-10">
                                               <textarea name="body" id="text">
                                                    
                                                </textarea>
                                                <script> CKEDITOR.replace( 'text' );</script>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group has-success">
                                            <div class="row">
                                                <div class="col-md-2 offset-md-2">
                                                    <input type="submit" value="Submit" class="btn btn-primary">
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>
@endsection

resources/views/backend/post/edit.blade.php
@extends('backend.layouts.master')

@push('title','Post')

@push('css')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
@endpush

@section('content')
    
<div class="animated fadeIn">

    <div class="row">

        <div class="col-lg-12">
            <div class="card">
                <div class="card-body card-header">
                    <h4 class="box-title">Post </h4>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card-body">
                            @if (session('status'))
                                <div class="alert alert-success">
                                    {{ session('status') }}
                                </div>
                            @endif
                            <form action="{{ route('post.update',$post->id) }}" method="post" enctype="multipart/form-data">
                                @csrf
                                @method('put')
                                    <div class="form-group has-success">
                                        <div class="row">
                                            <div class="col-md-2">
                                                <label for="title" class="mt-2">Title</label>
                                            </div>
                                            <div class="col-md-10">
                                                <input id="title" name="title" type="text" class="form-control" placeholder="Enter Title" value='{{ $post->title }}'>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group has-success">
                                        <div class="row">
                                            <div class="col-md-2">
                                                <label for="cat" class="mt-2">Category</label>
                                            </div>
                                            <div class="col-md-4">
                                                <select class="form-control" name="cat_id" id="cat">
                                                    
                                                    @foreach ($categorys as $item)
                                                        <option {{ ( $item->id == $post->category->id) ? 'selected' : '' }} value="{{ $item->id}}">{{ $item->name }}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group has-success">
                                        <div class="row">
                                            <div class="col-md-2">
                                                <label for="tag" class="mt-2">Tag</label>
                                            </div>
                                            <div class="col-md-4">
                                                @foreach ($tags as $item)
                                                    <input type="checkbox" name='tags[]' value="{{$item->id}}" class="mr-2">{{$item->name}}
                                                @endforeach
                                                
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group has-success">
                                        <div class="row">
                                            <div class="col-md-2">
                                                <label class="mt-2">Image</label>
                                            </div>
                                            <div class="col-md-2">
                                                <img src="{{ asset('/uploads/post/'.$post->image)}}" alt="" width="150" height="100">
                                            </div>
                                            <div class="col-md-4">
                                               <input type="file" name="image">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group has-success">
                                        <div class="row">
                                            <div class="col-md-2">
                                                <label for="text" class="mt-2">Body</label>
                                            </div>
                                            <div class="col-md-10">
                                               <textarea name="body" id="text">
                                                    {{ $post->body }}
                                                </textarea>
                                                <script> CKEDITOR.replace( 'text' );</script>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group has-success">
                                            <div class="row">
                                                <div class="col-md-2 offset-md-2">
                                                    <input type="submit" value="Submit" class="btn btn-primary">
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


</div>
@endsection

resources/views/backend/post/index.blade.php
@extends('backend.layouts.master')

@push('title','Post')

@push('css')
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
@endpush

@section('content')
    
<div class="animated fadeIn">

    <div class="row">

        <div class="col-lg-12">
            <div class="card">
                <div class="card-body card-header">
                    <h4 class="box-title">Post </h4>
                </div>
                <div class="card-body">
                    <a class="btn btn-success mb-2" href="{{ route('post.create') }}">Add New</a>
                    @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif
                    <table id="example" class="table text-center table-bordered">
                        <thead>
                            <tr>
                               <th>Sl No</th>
                               <th>Title</th>
                               <th>Body</th>
                               <th>Category</th>
                               <th>Image</th>
                               <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @php
                                $i = 1;
                            @endphp
                            @foreach ($data as $item)
                            <tr>
                                <td>{{ $i++ }}</td>
                                <td>{{ $item->title }}</td>
                                <td>{!! html_entity_decode(str_limit($item->body,'20')) !!}</td>
                                <td>{{ $item->category->name }}</td>
                                <td><img width="100" height="50" src="{{ asset('/uploads/post/'.$item->image)}}" alt=""></td>
                                <td><a class="btn btn-info mr-2" href="{{ route('post.edit',$item->id) }}">Edit </a>
                                    <form class="d-inline" action="{{ route('post.destroy',$item->id) }}" method="post">
                                        @csrf
                                        @method('delete')
                                        <button class="btn btn-danger" onclick="return confirm('Are You Sure?')"> Delete</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    {{ $data->links()}}
                </div>
            </div>
        </div>
    </div>


</div>
@endsection